[package]
name = "haumaru_api"
version = "0.1.0"
authors = ["Shane Gibbs <shane@hands.net.nz>"]

[dependencies]
log = "*"
notify = "*"
rusqlite = "0.7.3"
time = "*"
rust-crypto = "*"
rustc-serialize = "*"
env_logger = "*"
regex = "*"
serde = "^0.7"
serde_macros = "^0.7"
serde_yaml = "^0.2"

#[target.'cfg(apple)'.dependencies]
#fsevent =  { git = "https://github.com/shanegibbs/fsevent-rust.git" }
